timing: true
debug: false
stop_at_error: false
likelihood:
  baryons_lsst_y1.lsst_3x2pt:
    path: ./external_modules/data/baryons_lsst_y1
    data_file: LSST_Y1_emu_3x2pt_Magneticum_C13_M1.dataset
    create_baryon_pca: false
    use_baryonic_simulations_for_dv_contamination: false
    print_datavector: false
    accuracyboost: 1.0
    integration_accuracy: 0
    kmax_boltzmann: 5.0
    non_linear_emul: 2
params:
  As_1e9:
    prior:
      min: 0.5
      max: 10
    ref:
      dist: norm
      loc: 0.9571466
      scale: 0.1
    proposal: 0.1
    latex: 10^9 A_\mathrm{s}
    drop: true
    renames: A
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.96605
      scale: 0.005
    proposal: 0.005
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 67.5
      scale: 2
    proposal: 1
    latex: H_0
  omegabh2:
    prior:
      dist: norm
      loc: 0.022097812500000005
      scale: 0.0016
    ref:
      dist: norm
      loc: 0.022097812500000005
      scale: 0.005
    proposal: 0.005
    latex: \Omega_\mathrm{b} h^2
  omegam:
    prior:
      min: 0.05
      max: 0.9
    ref:
      dist: norm
      loc: 0.4
      scale: 0.01
    proposal: 0.01
    latex: \Omega_\mathrm{m}
    drop: true
  w0pwa:
    value: -1.0
    latex: w_{0,\mathrm{DE}}+w_{a,\mathrm{DE}}
  w:
    value: -1.0
    latex: w_{0,\mathrm{DE}}
  mnu:
    value: 0.06
  tau:
    value: 0.0697186
    latex: \tau_\mathrm{reio}
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
  omegab:
    derived: 'lambda omegabh2, H0: omegabh2/(H0/100)**2'
    latex: \Omega_\mathrm{b}
  omegach2:
    value: 'lambda omegam, omegabh2, mnu, H0: omegam*(H0/100)**2 - omegabh2 - (mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
  wa:
    value: 'lambda w0pwa, w: w0pwa - w'
    latex: w_{a,\mathrm{DE}}
  omegal:
    latex: \Omega_\Lambda
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  sigma8:
    latex: \sigma_8
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
  rdrag:
    latex: r_\mathrm{drag}
  yheused:
    latex: Y_P^\mathrm{BBN}
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  LSST_DZ_L1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^1
  LSST_DZ_L2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^2
  LSST_DZ_L3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^3
  LSST_DZ_L4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^4
  LSST_DZ_L5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^5
  LSST_BMAG_1:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^1
  LSST_BMAG_2:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^2
  LSST_BMAG_3:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^3
  LSST_BMAG_4:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^4
  LSST_BMAG_5:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^5
  LSST_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^1
  LSST_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^2
  LSST_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^3
  LSST_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^4
  LSST_DZ_S5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^5
  LSST_B1_1:
    value: 1.24
    latex: b_\mathrm{1-LSST}^1
  LSST_B1_2:
    value: 1.36
    latex: b_\mathrm{1-LSST}^2
  LSST_B1_3:
    value: 1.47
    latex: b_\mathrm{1-LSST}^3
  LSST_B1_4:
    value: 1.6
    latex: b_\mathrm{1-LSST}^4
  LSST_B1_5:
    value: 1.76
    latex: b_\mathrm{1-LSST}^5
  LSST_A1_1:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: 0.5
      scale: 0.1
    proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^1
  LSST_A1_2:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: 0.0
      scale: 0.1
    proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^2
  LSST_M1:
    value: 0.0
    latex: m_\mathrm{LSST}^1
  LSST_M2:
    value: 0.0
    latex: m_\mathrm{LSST}^2
  LSST_M3:
    value: 0.0
    latex: m_\mathrm{LSST}^3
  LSST_M4:
    value: 0.0
    latex: m_\mathrm{LSST}^4
  LSST_M5:
    value: 0.0
    latex: m_\mathrm{LSST}^5
  LSST_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{LSST}^1
  LSST_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{LSST}^2
  LSST_BARYON_Q3:
    value: 0.0
    latex: Q3_\mathrm{LSST}^3
  LSST_BARYON_Q4:
    value: 0.0
    latex: Q4_\mathrm{LSST}^4
theory:
  camb:
    path: ./external_modules/code/CAMB
    stop_at_error: false
    use_renames: true
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.1
      lens_potential_accuracy: 1.0
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 20
emulator:
  probe: 3x2pt
  io:
    savedir: ./projects/baryons_lsst_y1/emu/yaml_files/y1_3x2pt/Magneticum_C13/emu_output
    emudir: /xdisk/timeifler/pranjalrs/baryons_lsst_y1_emu/y1_3x2pt/Magneticum_C13/
    chainname: chain_M1
    save_train_data: true
    save_intermediate_model: true
  shear_calib:
    mask: ./projects/baryons_lsst_y1/data/emu_masks/shear_calib_mask.npy
    prior_std: 0.005,0.005,0.005,0.005,0.005
  baryons:
    n_pcas_baryon: 3
    prior_Q1: -50.,50.
    prior_Q2: -50.,50.
    prior_Q3: -50.,50.
  galaxy_bias:
    mask: ./projects/baryons_lsst_y1/data/emu_masks/bias_mask.npy
    bias_fid: 1.24,1.36,1.47,1.60,1.76
    bias_prior: 0.8, 3.0
  training:
    emu_type: nn
    nn_model: 0
    dv_fid: ./projects/baryons_lsst_y1/data/data_vector/lsst_y1_theory_Magneticum_C13.modelvector
    chi_sq_cut: 1e+5
    n_train_iter: 4
    n_lhs: 16000
    n_resample: 16000
    batch_size: 80
    n_epochs: 50
  sampling:
    scalecut_mask: ./projects/baryons_lsst_y1/data/masks/LSST_Y1_3x2pt_M1.mask
    n_mcmc: 40000
    n_emcee_walkers: 100
    n_burn_in: 20000
    n_thin: 10
    temper0: 0.02
    temper_increment: 0.05
